---
- hosts: localhost
  connection: local

  vars:
    resource_group_name: BlobToS3Persister-rg
    azure_location: germanywestcentral

  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{resource_group_name}}"
      location: "{{azure_location}}"
        
#  - name: Create a function app
#    azure_rm_functionapp:
#      resource_group: myResourceGroup
#      name: myFunctionApp
#      storage_account: myStorageAccount